#!/usr/bin/env python3
# Copyright (c) 2026 JG Systems Consulting Ltd. MIT License (see LICENSE).
# SPDX-License-Identifier: MIT
"""
Generate docs/packs.html, the browsable skill-reference page (RR-B-30), from SKILLS.md.

The page is the single source's downstream artifact: it parses the SKILLS.md table
(slug, source licence, description) and the version from RELEASE-INFO.txt, then emits a
self-contained, design-system-compliant HTML page with a client-side filter box. No
third-party assets, no CDN. Regenerate after any pack/SKILLS.md change so it cannot drift
(RR-B-00). Brand tokens (fonts plus :root) are not stored here: they are extracted from the
BRAND-TOKENS marker block in docs/index.html at render time (P13). Em dashes are stripped
from emitted copy (RR-B-28).
"""
import re
import sys
import html
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def deslop(text: str) -> str:
    """Remove em dashes from emitted copy (RR-B-28). Replace with a comma + space,
    collapsing any surrounding spaces so ' — ' becomes ', '."""
    text = re.sub(r"\s*—\s*", ", ", text)
    return text


def parse_skills() -> list[dict]:
    md = (ROOT / "SKILLS.md").read_text(encoding="utf-8")
    rows = []
    for m in re.finditer(r"^\|\s*\[`([^`]+)`\]\(([^)]+)\)\s*\|\s*([^|]+?)\s*\|\s*(.+?)\s*\|\s*$", md, re.M):
        slug, path, licence, desc = m.groups()
        rows.append({
            "slug": slug.strip(),
            "path": path.strip(),
            "licence": deslop(licence.strip()),
            "desc": deslop(desc.strip()),
        })
    return rows


def version() -> str:
    ri = (ROOT / "RELEASE-INFO.txt").read_text(encoding="utf-8")
    m = re.search(r"Version:\s*([0-9]+\.[0-9]+\.[0-9]+)", ri)
    return m.group(1) if m else "0.0.0"


BRAND_BEGIN = "/* BRAND-TOKENS:BEGIN"
BRAND_END = "/* BRAND-TOKENS:END"
BRAND_PLACEHOLDER = "__BRAND_TOKENS__"


def slice_brand_tokens(text: str) -> str:
    """Exclusive interior between the BRAND-TOKENS BEGIN and END marker lines.

    docs/index.html is the single source of truth for brand tokens (P13); the
    BEGIN and END comment lines themselves are not part of the slice. Raises
    ValueError (a plain Exception, never SystemExit) on missing, duplicated,
    reversed, or unbalanced markers so importers of brand_tokens()/render()
    (tooling/check_release.py rr-b-30) see a normal exception.
    """
    lines = text.splitlines()
    begins = [i for i, ln in enumerate(lines) if ln.startswith(BRAND_BEGIN)]
    ends = [i for i, ln in enumerate(lines) if ln.startswith(BRAND_END)]
    if len(begins) != 1 or len(ends) != 1:
        raise ValueError(
            f"expected exactly one BRAND-TOKENS BEGIN and one END marker line, "
            f"found {len(begins)} BEGIN / {len(ends)} END"
        )
    if begins[0] >= ends[0]:
        raise ValueError("BRAND-TOKENS:BEGIN must precede BRAND-TOKENS:END")
    return "\n".join(lines[begins[0] + 1:ends[0]])


def brand_tokens() -> str:
    """The brand-token block copied verbatim from docs/index.html."""
    index = ROOT / "docs" / "index.html"
    return slice_brand_tokens(index.read_text(encoding="utf-8"))


REPO = "https://github.com/jgsystemsconsulting/jgs-sector-signposts"
PAGES = "https://jgsystemsconsulting.github.io/jgs-sector-signposts"


def render(rows: list[dict], ver: str) -> str:
    n_content = len(rows)
    cells = []
    for r in rows:
        slug = html.escape(r["slug"])
        licence = html.escape(r["licence"])
        # Frontmatter descriptions carry markdown (**bold**, `code`); render them,
        # keep the filter copy plain.
        plain = r["desc"].replace("**", "").replace("`", "")
        desc = html.escape(r["desc"])
        desc = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", desc)
        desc = re.sub(r"`([^`]+)`", r"<code>\1</code>", desc)
        href = f"{REPO}/blob/main/{r['path']}"
        # data-text keeps source case so identity tokens survive mint substitution;
        # the filter JS lowercases both sides at query time.
        data = html.escape(f"{r['slug']} {r['licence']} {plain}", quote=True)
        cells.append(
            f'<tr data-text="{data}">'
            f'<td class="slug"><a href="{href}">{slug}</a></td>'
            f'<td class="lic">{licence}</td>'
            f'<td class="desc">{desc}</td></tr>'
        )
    rows_html = "\n".join(cells)

    html_out = f"""<!doctype html>
<!--
  Copyright (c) 2026 JG Systems Consulting Ltd. MIT License (see ../LICENSE).
  SPDX-License-Identifier: MIT
  GENERATED by tooling/gen_packs_page.py from SKILLS.md. Do not hand-edit (RR-B-00).
  RR-B-30 browsable skill reference. Self-contained (inline CSS/JS, no third-party asset).
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="dark">
<title>Pack reference, Rail, Space, and Maritime Knowledge Packs ({n_content} skills)</title>
<meta name="description" content="Browse and filter all {n_content} Rail, Space, and Maritime knowledge-pack skills by slug, source licence, and coverage for coding agents.">
<link rel="canonical" href="{PAGES}/packs.html">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' fill='%230a0a0b'/%3E%3Ctext x='16' y='23' font-family='monospace' font-size='22' font-weight='700' text-anchor='middle' fill='%23f4f2ec'%3E%C2%A7%3C/text%3E%3C/svg%3E">
<meta property="og:type" content="website">
<meta property="og:title" content="Pack reference, Rail, Space, and Maritime Knowledge Packs">
<meta property="og:description" content="Browse and filter all {n_content} Rail, Space, and Maritime knowledge-pack skills by slug, source licence, and coverage.">
<meta property="og:url" content="{PAGES}/packs.html">
<meta property="og:image" content="{PAGES}/assets/og-default.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Pack reference, Rail, Space, and Maritime Knowledge Packs">
<meta name="twitter:description" content="Browse and filter all {n_content} Rail, Space, and Maritime knowledge-pack skills.">
<meta name="twitter:image" content="{PAGES}/assets/og-default.png">
<style>
__BRAND_TOKENS__
*{{box-sizing:border-box}}
html{{-webkit-text-size-adjust:100%}}
body{{margin:0;background:var(--ink);color:var(--mute-2);font-family:var(--sans);font-size:16px;line-height:1.6;-webkit-font-smoothing:antialiased}}
.wrap{{max-width:1200px;margin:0 auto;padding-left:var(--pad-x);padding-right:var(--pad-x)}}
a{{color:var(--text-hi);text-decoration:none;border-bottom:1px solid var(--line-2)}}
a:hover{{border-bottom-color:var(--paper)}}
a:focus-visible,input:focus-visible{{outline:2px solid var(--paper);outline-offset:2px}}
h1{{font-family:var(--mono);color:var(--text-hi);letter-spacing:-0.02em;font-weight:700;margin:0;font-size:clamp(1.6rem,4vw,2.4rem)}}
.label{{font-family:var(--mono);text-transform:uppercase;letter-spacing:0.14em;font-size:0.6875rem;font-weight:700;color:var(--mute)}}
.mast{{border-bottom:1px solid var(--line);background:var(--ink-2)}}
.mast .wrap{{display:flex;flex-wrap:wrap;gap:10px 28px;padding-top:12px;padding-bottom:12px}}
.mast .label span{{color:var(--text)}}
header.hd{{border-bottom:1px solid var(--line);padding-top:var(--pad-section);padding-bottom:2rem}}
header.hd p{{margin:1rem 0 0;max-width:64ch;color:var(--text)}}
.tools{{display:flex;flex-wrap:wrap;gap:10px 14px;align-items:center;margin-top:1.4rem;padding:10px 12px;background:var(--ink-2);border:1px solid var(--line)}}
input#q{{font-family:var(--mono);font-size:0.9rem;background:var(--ink);border:1px solid var(--line);color:var(--text-hi);padding:10px 12px;flex:1 1 16rem;min-width:min(280px,100%)}}
input#q::placeholder{{color:var(--mute)}}
#count{{font-family:var(--mono);font-size:0.75rem;color:var(--mute);text-transform:uppercase;letter-spacing:0.1em;white-space:nowrap}}
.nav{{margin-top:1.15rem;font-family:var(--mono);font-size:0.8rem}}
section{{padding-top:1.75rem;padding-bottom:var(--pad-section)}}
table{{width:100%;border-collapse:collapse;border:1px solid var(--line);background:var(--ink)}}
thead th{{font-family:var(--mono);text-transform:uppercase;letter-spacing:0.1em;font-size:0.6875rem;font-weight:700;color:var(--mute);text-align:left;padding:12px 16px;background:var(--ink-2);border-bottom:1px solid var(--line);position:sticky;top:0;z-index:2;box-shadow:0 1px 0 var(--line)}}
tbody td{{padding:13px 16px;border-bottom:1px solid var(--line);vertical-align:top;font-size:0.9rem}}
tbody tr:hover td{{background:var(--ink-3)}}
tbody tr:last-child td{{border-bottom:none}}
td.slug a{{font-family:var(--mono);font-weight:700;color:var(--text-hi);font-size:0.85rem;white-space:nowrap}}
td.lic{{font-family:var(--mono);font-size:0.75rem;color:var(--mute-2);white-space:nowrap}}
td.desc{{color:var(--text)}}
tr.hidden{{display:none}}
#empty{{display:none;padding:24px 16px;color:var(--mute-2);font-family:var(--mono);font-size:0.85rem;border:1px solid var(--line);background:var(--ink-2);margin-top:12px}}
footer{{padding-top:32px;padding-bottom:48px;color:var(--mute);border-top:1px solid var(--line)}}
footer .label{{display:block;margin-bottom:8px}}
@media (max-width:760px){{
  thead{{display:none}}
  table,tbody,tr,td{{display:block;width:100%}}
  table{{border:none;background:transparent}}
  tbody tr{{border:1px solid var(--line);margin-bottom:8px;padding:8px 0;background:var(--ink-2)}}
  tbody tr:hover td{{background:transparent}}
  tbody td{{border-bottom:none;padding:6px 16px}}
  td.lic{{color:var(--mute);white-space:normal}}
}}
@media (prefers-reduced-motion:reduce){{*{{transition:none!important;animation:none!important}}}}
</style>
</head>
<body>

<!-- Masthead and footer chrome stay hand-mirrored in docs/index.html; only the BRAND-TOKENS block auto-syncs. -->
<div class="mast"><div class="wrap">
  <span class="label">CLASSIFICATION: <span>PUBLIC</span></span>
  <span class="label">LICENCE: <span>MIT (TOOLING)</span></span>
  <span class="label">DOC-ID: <span>JGS-KP/REF</span></span>
  <span class="label">REV: <span>{ver}</span></span>
</div></div>

<header class="hd"><div class="wrap">
  <h1>The full catalogue, {n_content} skills</h1>
  <p>Every knowledge pack in the release, with its source licence and what it covers. Each pack
  is an Agent Skill you invoke by its slug. Type to filter by name, publisher, licence, or topic.
  Click a slug to open its <code>SKILL.md</code> on GitHub.</p>
  <div class="tools">
    <input id="q" type="search" placeholder="filter, e.g. risk, public domain, CC BY" aria-label="Filter packs">
    <span id="count"></span>
  </div>
  <div class="nav"><a href="index.html">&larr; Back to the overview</a></div>
</div></header>

<section><div class="wrap">
  <table>
    <thead><tr><th>Pack</th><th>Source licence</th><th>What it covers</th></tr></thead>
    <tbody id="rows">
{rows_html}
    </tbody>
  </table>
  <div id="empty">No packs match that filter.</div>
</div></section>

<footer><div class="wrap">
  <p style="margin:0;font-size:0.9rem">
    <a href="index.html">Overview</a> ·
    <a href="{REPO}">Repository</a> ·
    <a href="{REPO}/blob/main/SKILLS.md">SKILLS.md</a> ·
    <a href="{REPO}/blob/main/docs/skill-usage.md">Usage</a>
  </p>
</div></footer>

<script>
(function(){{
  var q=document.getElementById('q'),rows=[].slice.call(document.querySelectorAll('#rows tr')),
      count=document.getElementById('count'),empty=document.getElementById('empty'),total=rows.length;
  function upd(){{
    var t=q.value.trim().toLowerCase(),shown=0;
    rows.forEach(function(r){{
      var hit=!t||(r.getAttribute('data-text')||'').toLowerCase().indexOf(t)>-1;
      r.classList.toggle('hidden',!hit); if(hit)shown++;
    }});
    count.textContent=shown+' / '+total+' shown';
    empty.style.display=shown?'none':'block';
  }}
  q.addEventListener('input',upd); upd();
}})();
</script>

</body>
</html>
"""

    return html_out.replace(BRAND_PLACEHOLDER, brand_tokens())


def main() -> int:
    rows = parse_skills()
    if not rows:
        print("ERROR: no pack rows parsed from SKILLS.md", file=sys.stderr)
        return 1
    out = ROOT / "docs" / "packs.html"
    out.write_text(render(rows, version()), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({len(rows)} packs)")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        print(
            "restore exactly one BRAND-TOKENS:BEGIN and one BRAND-TOKENS:END "
            "marker line in docs/index.html, then rerun",
            file=sys.stderr,
        )
        raise SystemExit(1) from e

